#java maven azure pipeline
trigger:
  branches:
    include:
    - master
    - test
resources:
  repositories:
    - repository: templates
      type: git
      name: Test2/Templates-Daniel
    - repository: variables
      type: git
      name: Test2/Templates-Daniel

variables:
  - template: Variables/variables.yml@variables
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
  - template: Java/java-maven.yml@templates
